openapi: 3.0.0
info:
  title: WebApplicationApi
  version: '1.0'
  description: |-
    A web application API which primary function is to serve as a platform for selling
    and buying used items. 
servers:
  - url: 'http://localhost:3000'
paths:
  /User:
    post:
      summary: ''
      operationId: post-User
      responses:
        '200':
          description: User Successfully Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          description: Missing or Incorrect Data in Request
        '418':
          description: The username is already taken
          content:
            application/json:
              schema:
                $ref: ''
      description: Create A New User
      parameters: []
    parameters: []
    delete:
      description: ''
  /User/login:
    post:
      summary: ''
      operationId: 'post-User[login]'
      responses:
        '201':
          description: User successfully logged in
        '400':
          description: Missing or incorrect data in the request
        '418':
          description: Username or password do not match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
      description: Log in with your Username and password
    parameters: []
  /User/login/Products:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          description: Proucts Shown
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
      operationId: get-User-login-Products
      description: Show Products Listed to Buy
    post:
      summary: ''
      operationId: post-User-login-Products
      responses:
        '200':
          description: Product is Added
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User is not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
      description: Create New products to sell
    delete:
      summary: ''
      operationId: delete-User-login-Products
      responses:
        '201':
          description: Item has been deleted
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
      description: To Delete an Item
    put:
      summary: ''
      operationId: put-User-login-Products
      responses:
        '201':
          description: Product Information has been Updated
        '401':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
      description: Update Product Information
    patch:
      summary: ''
      operationId: patch-User-login-Products
      responses:
        '201':
          description: Product has been updated
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User Is not logged in
      description: Update Product
  /User/login/Category/Products:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          description: Products in this category are shown
        '401':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User Is not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
      operationId: get-User-login-Products-Category
      description: Show products in this category
    parameters: []
    post:
      summary: ''
      operationId: post-User-login-Category-Products
      responses:
        '201':
          description: New category is Created
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User is not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
      description: Create a new category
    delete:
      summary: ''
      operationId: delete-User-login-Category-Products
      responses:
        '201':
          description: Category successfully created
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
      description: Delete a category
  /listings:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '201':
          description: Listings are shown
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: Refresh and try again
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
      operationId: get-listings
      description: show all user listings
    post:
      summary: ''
      operationId: post-listings
      description: Create a new listing
      responses:
        '201':
          description: New listing Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: Refresh and try again
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
    options:
      summary: ''
      operationId: options-listings
      responses:
        '201':
          description: Items shown
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listings'
        '400':
          description: 'Missing or incorrect data in the request '
        '418':
          description: Refresh and try again
      description: Search for listing based on the category
components:
  schemas:
    user:
      title: user
      type: object
      description: Creating A New User
      x-examples:
        example-1:
          First Name: David
          Last Name: Beckham
          Username: DBeckham
          DOB: 18/05/1989
          Country: Ireland
          City: Dublin
          Address: Street 67
          Email: David@demo.com
          Password: 120Jasd2
      properties:
        First Name:
          type: string
          example: David
          description: |
            Enter your First name
        Last Name:
          type: string
          example: Beckham
          description: |
            Enter your last name
        Username:
          type: string
          example: DBeckham
          description: Choose a username for your account
        DOB:
          type: string
          example: 18-05-1989
          description: Enter your date of birth
        Country:
          type: string
          example: Ireland
          description: Enter the country you live in
        City:
          type: string
          example: Dublin
          description: The city that you live in
        Address:
          type: string
          example: Street 67
          description: Your Address where you are living
        Email:
          type: string
          format: email
          example: David@demo.com
          description: Enter your email
        Password:
          type: string
          example: 120Jasd2
          format: password
          description: Choose a strong password for your account
      required:
        - First Name
        - Last Name
        - Username
        - DOB
        - Country
        - City
        - Address
        - Email
        - Password
    Login:
      title: Login
      type: object
      description: Login With Username and password
      properties:
        Username:
          type: string
          example: DBeckham
          description: |
            Log in with your username
        Password:
          type: string
          format: password
          example: 120Jasd2
          description: |
            Log in with your password
      required:
        - Username
        - Password
      x-examples:
        example-1:
          Username: DBeckham
          Password: 120Jasd2
    Products:
      title: Products
      type: object
      description: Product Information
      x-examples:
        example:
          Title: T-Shirt
          Description: Yellow Cotton T-shirt In good condition.
          Category: Clothes
          Location: Dublin
          Asked Price: 15Euro
          Date of posting: 22-01-21
          Delivery Type: Collection Only!
          Product Id: T20
          Seller Name: Brandon
          Seller Contact Number: '0872039332'
      properties:
        Title:
          type: string
          description: Name of the product
          example: T-Shirt
        Description:
          type: string
          description: |
            Desscription of the product: color, size, condition etc
          example: Yellow Cotton T-shirt In good condition.
        Category:
          type: string
          description: 'Category of product: clother, shoes, toys, accessories etc'
          example: Clothes
        Location:
          type: string
          description: Location of the product
          example: Dublin
        Asked Price:
          type: string
          description: How much does the Item cost
          example: 15Euro
        Date of posting:
          type: string
          description: What date was the item posted
          example: 22-01-21
        Delivery Type:
          type: string
          description: Is it shipped or for collection
          example: Collection Only!
        Product Id:
          type: string
          description: Product code
          example: T20
        Seller Name:
          type: string
          example: Brandon
          description: Sellers Name
        Seller Contact Number:
          type: string
          example: '0872039332'
          description: Sellers mobile number
        Images:
          type: string
          example: Image 1. Image 2. Image 3.
          description: Picture of product
      required:
        - Title
        - Description
        - Category
        - Location
        - Asked Price
        - Date of posting
        - Delivery Type
        - Product Id
        - Seller Name
        - Seller Contact Number
        - Images
    Category:
      title: Category
      type: object
      description: Categories of the products
      properties:
        Clothes:
          type: string
        Shoes:
          type: string
        Toys:
          type: string
        Homeware:
          type: string
        Electronics:
          type: string
        Accessories:
          type: string
        Books:
          type: string
      required:
        - Clothes
        - Shoes
        - Toys
        - Homeware
        - Electronics
        - Accessories
        - Books
      x-examples:
        example-1:
          Clothes: string
          Shoes: string
          Toys: string
          Homeware: string
          Electronics: string
          Accessories: string
          Books: string
    Listings:
      title: Listings
      type: object
      x-examples:
        example-1:
          Category:
            - Title: T-Shirt
              Description: Yellow Cotton T-shirt In good condition.
              Category: Clothes
              Location: Dublin
              Asked Price: 15Euro
              Date of posting: 22-01-21
              Delivery Type: Collection Only!
              Product Id: T20
              Seller Name: Brandon
              Seller Contact Number: '0872039332'
              Images: Image 1. Image 2. Image 3.
          Location:
            Title: T-Shirt
            Description: Yellow Cotton T-shirt In good condition.
            Category: Clothes
            Location: Dublin
            Asked Price: 15Euro
            Date of posting: 22-01-21
            Delivery Type: Collection Only!
            Product Id: T20
            Seller Name: Brandon
            Seller Contact Number: '0872039332'
            Images: Image 1. Image 2. Image 3.
          Date of posting:
            Title: T-Shirt
            Description: Yellow Cotton T-shirt In good condition.
            Category: Clothes
            Location: Dublin
            Asked Price: 15Euro
            Date of posting: 22-01-21
            Delivery Type: Collection Only!
            Product Id: T20
            Seller Name: Brandon
            Seller Contact Number: '0872039332'
            Images: Image 1. Image 2. Image 3.
      properties:
        Location:
          $ref: '#/components/schemas/Products'
        Date of posting:
          $ref: '#/components/schemas/Products'
        Category:
          $ref: '#/components/schemas/Category'
